version: 1
disable_existing_loggers: false
formatters:
  basic:
    format: "%(asctime)s:pid_%(process)d:%(module)s:<%(levelname)s> %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
  file_debug:
    class: logging.FileHandler
    level: INFO
    formatter: basic
    filename: info.log
#  file_error:
#    class: logging.FileHandler
#    level: ERROR
#    formatter: basic
#    filename: error.log
loggers:
  __main__:
    level: DEBUG
    handlers:
    - console
    - file_debug
#    - file_error
    propagate: true
